/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Spaceship(props) {
  const { nodes, materials } = useGLTF('/home/hero/spaceship.glb');
  return (
    <group
      {...props}
      dispose={null}
      rotation={[-Math.PI / 2, 0.2, -0.9]}
      scale={props.scale || 0.4}
      position={props.position || [1.3, -0.5, 0]}
    >
      <group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_54.geometry}
            material={materials.material_19}
            position={[0.165, 3.666, -1.684]}
            rotation={[1.615, 0.928, 2.349]}
            scale={0.474}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_20.geometry}
            material={materials.Barrel}
            position={[-0.263, 3.988, -0.239]}
            rotation={[0.549, 0.537, 0.363]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.Alien}
            position={[-0.689, 1.997, 0.207]}
            rotation={[-0.096, 0.001, 0.361]}
            scale={0.485}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_46.geometry}
            material={materials.Books}
            position={[-1.281, 3.731, -0.439]}
            rotation={[-2.552, 1.12, -2.667]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_48.geometry}
            material={materials.Books}
            position={[-2.237, 3.535, -0.735]}
            rotation={[0.118, -0.142, 0.051]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials['TreasureChest.001']}
            position={[-1.744, 3.134, -1.202]}
            rotation={[2.133, -1.266, 2.668]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_52.geometry}
            material={materials.Lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.Cockpit}
            position={[-0.229, 0.78, -0.109]}
            rotation={[-0.096, 0.001, 0.361]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_26.geometry}
            material={materials.material}
            position={[-1.814, 3.647, -0.131]}
            rotation={[0.636, -0.011, 0.88]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.Engine}
            position={[-0.231, 0.581, -2.185]}
            rotation={[1.475, 0.361, -0.001]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.Flame}
            position={[-0.178, 0.504, -3.312]}
            rotation={[1.475, 0.361, -0.001]}
            scale={1.362}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.material_14}
            position={[-1.258, 3.688, -0.611]}
            rotation={[1.9, -0.055, -1.912]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials.Piano}
            position={[-0.811, 2.744, -1.484]}
            rotation={[0.985, 0.135, 0.512]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Ropes}
            position={[-0.146, 0.81, 3.233]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Ship}
            position={[-0.229, 0.78, -0.109]}
            rotation={[-0.096, 0.001, 0.361]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_28.geometry}
            material={materials.Suitcase}
            position={[-0.881, 3.361, -1.411]}
            rotation={[-2.159, -0.162, 2.963]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.Window}
            position={[-0.915, 2.632, 0.158]}
            rotation={[-0.096, 0.001, 0.361]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/home/hero/spaceship.glb');
